# Generated by Django 3.1.1 on 2020-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200913_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
